<template>
    <div class="h-full w-full flex mt-32 flex-row space-x-4  text-white text-xl">
        <div class="flex flex-col w-full p-2">
            <h1 class="font-extralight text-purple-400 text-5xl">Oops ! This link could not be found :c</h1>
            <div class="space-y-4 p-4">
                <h2 class="text-4xl">Why am I seeing this ?</h2>
                <p class="text-purple-400">The link you clicked on has been generated by Nuz. A link shortening tool.
                    This link could not be found in our database.</p>
                <h3 class="text-3xl">This could be because:</h3>
                <ul class="list-disc px-8 text-2xl text-purple-400">
                    <li>The link was configured to expire by its registerer</li>
                    <li>The link was deleted by its registerer</li>
                    <li>The link registrer's account was deleted</li>
                    <li>There was a typo in the link you recieved.</li>
                </ul>
            </div>
        </div>
    </div>
</template>
<script setup>
</script>